import type { Edge, Node } from "reactflow";
import { NODE_TYPE_META } from "@/lib/constants";
import type { BowtieNodeData } from "@/lib/types/bowtie";

const X = {
  threat: 21,
  preventive: 271,
  topEvent: 521,
  mitigative: 771,
  consequence: 1021,
} as const;

const ESCALATION_EDGE_STYLE = { stroke: "#a855f7", strokeDasharray: "6 4" };

export type ExampleProject = {
  slug: string;
  title: string;
  industry: string;
  topEvent: string;
  contextNotes: string;
  summary: string;
  highlights: string[];
  nodes: Node<BowtieNodeData>[];
  edges: Edge[];
};

function node(
  id: string,
  type: BowtieNodeData["type"],
  x: number,
  y: number,
  data: Omit<BowtieNodeData, "type" | "typeLabel">,
): Node<BowtieNodeData> {
  return {
    id,
    type: "bowtieNode",
    position: { x, y },
    data: {
      type,
      typeLabel: NODE_TYPE_META[type].label,
      ...data,
    },
  };
}

function edge(id: string, source: string, target: string, style?: Edge["style"]): Edge {
  return {
    id,
    source,
    target,
    type: "smoothstep",
    style,
  };
}

export const EXAMPLE_PROJECTS: ExampleProject[] = [
  {
    slug: "ai-data-breach",
    title: "AI Data Breach",
    industry: "IT/Cloud",
    topEvent: "Sensitive data is exposed through an AI-assisted workflow",
    contextNotes:
      "Public demo scenario covering customer support copilots, retrieval pipelines, and incident response controls.",
    summary:
      "Shows how prompt injection, excessive connector access, and poor sharing practices can break containment in an enterprise AI workflow.",
    highlights: ["AI governance", "Privacy incident", "Access control"],
    nodes: [
      node("top-event", "top_event", X.topEvent, 320, {
        title: "Sensitive data is exposed through an AI-assisted workflow",
        description: "Confidential customer or employee information leaves approved boundaries through model use.",
        context: "Enterprise AI copilots connected to internal knowledge bases and outbound collaboration tools.",
      }),
      node("threat-prompt-injection", "threat", X.threat, 120, {
        title: "Prompt injection in a customer support copilot",
        description: "A malicious prompt causes the assistant to ignore guardrails and reveal restricted records.",
        cause: "Untrusted external user input",
        source: "Customer-facing AI channel",
      }),
      node("threat-excessive-access", "threat", X.threat, 320, {
        title: "Excessive retrieval permissions in the AI data layer",
        description: "The model can access repositories that were never approved for the use case.",
        cause: "Over-broad service account scope",
        source: "Internal vector store and file connectors",
      }),
      node("threat-public-share", "threat", X.threat, 520, {
        title: "Model output is copied into a public share",
        description: "Sensitive generated content is posted to an exposed collaboration space.",
        cause: "Manual handling error after generation",
        source: "Shared documents and messaging tools",
      }),
      node("barrier-policy-gateway", "preventive_barrier", X.preventive, 120, {
        title: "Prompt and output policy gateway",
        description: "Screens prompts and responses for jailbreak patterns, secrets, and prohibited disclosures.",
        barrierType: "engineering",
        owner: "AI Platform Team",
        performanceStandard: "All external prompts and responses pass real-time policy checks before release.",
        verificationMethod: "Weekly adversarial prompt tests with blocked-output review.",
        frequency: "Weekly",
      }),
      node("barrier-least-privilege", "preventive_barrier", X.preventive, 320, {
        title: "Least-privilege retrieval and connector allowlists",
        description: "Limits the model to approved data domains, schemas, and document collections.",
        barrierType: "engineering",
        owner: "Identity and Access Management",
        performanceStandard: "Service accounts are scoped to approved data sets only.",
        verificationMethod: "Monthly entitlement review and connector diff check.",
        frequency: "Monthly",
      }),
      node("barrier-dlp-review", "preventive_barrier", X.preventive, 520, {
        title: "DLP review before sharing AI outputs",
        description: "Requires automated classification and user confirmation before publishing generated content.",
        barrierType: "procedural",
        owner: "Business Operations",
        performanceStandard: "Restricted outputs cannot be shared without classification review.",
        verificationMethod: "Quarterly audit of sampled shares and DLP alerts.",
        frequency: "Quarterly",
      }),
      node("factor-filter-disabled", "escalation_factor", X.preventive, 410, {
        title: "Guardrail tuning is disabled during an urgent release",
        description: "An emergency deployment bypasses prompt-policy checks.",
        factor: "Change pressure weakens the preventive barrier.",
        supportLane: "preventive",
        supportAnchorX: X.preventive,
      }),
      node("control-change-gate", "escalation_factor_control", X.preventive, 620, {
        title: "Production policy changes require security approval",
        description: "Any reduction in model safety checks requires a documented exception and approver.",
        control: "Formal change gate for policy engine updates",
        supportLane: "preventive",
        supportAnchorX: X.preventive,
      }),
      node("barrier-token-revocation", "mitigative_barrier", X.mitigative, 220, {
        title: "Automated session kill and token revocation",
        description: "Cuts active sessions, blocks outbound connectors, and revokes compromised tokens immediately.",
        barrierType: "engineering",
        owner: "Security Operations",
        performanceStandard: "Containment actions start within five minutes of confirmed exposure.",
        verificationMethod: "Monthly playbook simulation and alert timing review.",
        frequency: "Monthly",
        chainIndex: 0,
      }),
      node("barrier-incident-playbook", "mitigative_barrier", X.mitigative, 470, {
        title: "Privacy breach notification and legal response playbook",
        description: "Coordinates impact assessment, regulator notification, and customer communications.",
        barrierType: "procedural",
        owner: "Privacy Office",
        performanceStandard: "Reportability decision and executive briefing completed within 24 hours.",
        verificationMethod: "Quarterly tabletop and after-action review.",
        frequency: "Quarterly",
        chainIndex: 0,
      }),
      node("consequence-pii", "consequence", X.consequence, 220, {
        title: "Customer PII is exposed outside approved recipients",
        description: "Names, contact information, or support history are disclosed to unauthorized parties.",
        impact: "Privacy harm, contract breach, and customer trust erosion.",
        severity: "high",
      }),
      node("consequence-reportable", "consequence", X.consequence, 470, {
        title: "Regulator-reportable AI privacy incident",
        description: "The organization must investigate, notify, and defend the incident to regulators.",
        impact: "Regulatory scrutiny, legal cost, and board escalation.",
        severity: "critical",
      }),
      node("factor-after-hours", "escalation_factor", X.mitigative, 90, {
        title: "No incident lead is available after hours",
        description: "Containment and notification steps stall because ownership is unclear overnight.",
        factor: "Staffing gap weakens mitigative response.",
        supportLane: "mitigative",
        supportAnchorX: X.mitigative,
      }),
      node("control-on-call-roster", "escalation_factor_control", X.mitigative, 130, {
        title: "24/7 cyber and privacy on-call roster",
        description: "Named responders and backups are drilled against the AI breach playbook.",
        control: "On-call coverage with quarterly response exercises",
        supportLane: "mitigative",
        supportAnchorX: X.mitigative,
      }),
    ],
    edges: [
      edge("e1", "threat-prompt-injection", "barrier-policy-gateway"),
      edge("e2", "barrier-policy-gateway", "top-event"),
      edge("e3", "threat-excessive-access", "barrier-least-privilege"),
      edge("e4", "barrier-least-privilege", "top-event"),
      edge("e5", "threat-public-share", "barrier-dlp-review"),
      edge("e6", "barrier-dlp-review", "top-event"),
      edge("e7", "top-event", "barrier-token-revocation"),
      edge("e8", "barrier-token-revocation", "consequence-pii"),
      edge("e9", "top-event", "barrier-incident-playbook"),
      edge("e10", "barrier-incident-playbook", "consequence-reportable"),
      edge("e11", "factor-filter-disabled", "barrier-least-privilege", ESCALATION_EDGE_STYLE),
      edge("e12", "control-change-gate", "factor-filter-disabled", ESCALATION_EDGE_STYLE),
      edge("e13", "factor-after-hours", "barrier-token-revocation", ESCALATION_EDGE_STYLE),
      edge("e14", "control-on-call-roster", "factor-after-hours", ESCALATION_EDGE_STYLE),
    ],
  },
  {
    slug: "municipal-water-contamination",
    title: "Municipal Water Contamination",
    industry: "Utilities",
    topEvent: "Treated drinking water becomes biologically contaminated before distribution",
    contextNotes:
      "Municipal utility example focused on treatment upsets, disinfectant control, and emergency response for potable water systems.",
    summary:
      "Demonstrates how treatment failures and network backflow can lead to a public-health event in a municipal water utility.",
    highlights: ["Municipal utility", "Public health", "Treatment assurance"],
    nodes: [
      node("mw-top-event", "top_event", X.topEvent, 320, {
        title: "Treated drinking water becomes biologically contaminated before distribution",
        description: "Potable water no longer meets microbiological safety limits entering the distribution system.",
        context: "Surface-water treatment plant feeding a municipal distribution network.",
      }),
      node("mw-threat-dose-failure", "threat", X.threat, 120, {
        title: "Disinfectant dosing pump failure",
        description: "Primary disinfection drops below target due to pump malfunction or empty chemical supply.",
        cause: "Mechanical failure and missed replenishment",
        source: "Chlorination system",
      }),
      node("mw-threat-filter-breakthrough", "threat", X.threat, 320, {
        title: "Filter breakthrough after turbidity spike",
        description: "Treatment barriers are overwhelmed during raw-water quality deterioration.",
        cause: "Storm-driven turbidity surge",
        source: "Clarification and filtration train",
      }),
      node("mw-threat-backflow", "threat", X.threat, 520, {
        title: "Cross-connection backflow into the network",
        description: "Contaminated water is drawn into the potable system during pressure loss.",
        cause: "Field connection not isolated",
        source: "Distribution network maintenance activity",
      }),
      node("mw-barrier-residual", "preventive_barrier", X.preventive, 120, {
        title: "Online disinfectant residual monitoring with alarms",
        description: "Operators receive immediate alarms when residual falls below operating limits.",
        barrierType: "engineering",
        owner: "Water Treatment Operations",
        performanceStandard: "Residual remains within approved operating band at all times.",
        verificationMethod: "Daily calibration and alarm test review.",
        frequency: "Daily",
      }),
      node("mw-barrier-clarifier", "preventive_barrier", X.preventive, 320, {
        title: "Turbidity hold-point before water leaves filtration",
        description: "Automatically prevents out-of-spec water from advancing to clear wells.",
        barrierType: "engineering",
        owner: "Process Control Team",
        performanceStandard: "Any turbidity excursion triggers diversion or shutdown.",
        verificationMethod: "Monthly challenge tests and historian review.",
        frequency: "Monthly",
      }),
      node("mw-barrier-backflow-program", "preventive_barrier", X.preventive, 520, {
        title: "Cross-connection control and isolation permits",
        description: "Requires inspected backflow prevention devices and work permits for system tie-ins.",
        barrierType: "procedural",
        owner: "Distribution Services",
        performanceStandard: "All high-risk connections have current protection and permit checks.",
        verificationMethod: "Quarterly field inspection sample.",
        frequency: "Quarterly",
      }),
      node("mw-factor-maint-backlog", "escalation_factor", X.preventive, 410, {
        title: "Maintenance backlog delays sensor repair",
        description: "Critical monitoring devices stay impaired longer than intended.",
        factor: "Equipment availability gap weakens preventive assurance.",
        supportLane: "preventive",
        supportAnchorX: X.preventive,
      }),
      node("mw-control-critical-spares", "escalation_factor_control", X.preventive, 620, {
        title: "Critical spares and repair priority list",
        description: "Essential treatment sensors and pumps have stocked replacements and escalation rules.",
        control: "Priority maintenance workflow for treatment-critical assets",
        supportLane: "preventive",
        supportAnchorX: X.preventive,
      }),
      node("mw-barrier-boil-advisory", "mitigative_barrier", X.mitigative, 220, {
        title: "Automatic boil-water advisory workflow",
        description: "Initiates customer notices, sampling plans, and regulator communication when contamination is confirmed.",
        barrierType: "procedural",
        owner: "Utility Incident Command",
        performanceStandard: "Public advisory decision is issued within two hours of confirmation.",
        verificationMethod: "Semiannual emergency exercise.",
        frequency: "Semiannual",
        chainIndex: 0,
      }),
      node("mw-barrier-flush-disinfect", "mitigative_barrier", X.mitigative, 470, {
        title: "Distribution flushing and targeted re-disinfection",
        description: "Contains spread by isolating affected zones and restoring residuals.",
        barrierType: "engineering",
        owner: "Network Operations",
        performanceStandard: "Affected zones are isolated and flushed per incident playbook.",
        verificationMethod: "After-action review after each drill or event.",
        frequency: "Quarterly",
        chainIndex: 0,
      }),
      node("mw-consequence-illness", "consequence", X.consequence, 220, {
        title: "Customers experience waterborne illness exposure",
        description: "Residents may consume unsafe water before the issue is contained.",
        impact: "Public health harm and loss of trust.",
        severity: "critical",
      }),
      node("mw-consequence-regulator", "consequence", X.consequence, 470, {
        title: "Regulatory enforcement and emergency oversight",
        description: "The utility faces mandatory reporting, investigation, and corrective orders.",
        impact: "Compliance action, financial cost, and political scrutiny.",
        severity: "high",
      }),
      node("mw-factor-comms-gap", "escalation_factor", X.mitigative, 90, {
        title: "Contact lists for key stakeholders are outdated",
        description: "Customers and health agencies are not alerted quickly enough.",
        factor: "Communications readiness weakens mitigative action.",
        supportLane: "mitigative",
        supportAnchorX: X.mitigative,
      }),
      node("mw-control-comms-drill", "escalation_factor_control", X.mitigative, 130, {
        title: "Quarterly emergency notification drill",
        description: "Tests outbound alert lists, spokesperson approval, and regulator contact paths.",
        control: "Routine contact verification and drill program",
        supportLane: "mitigative",
        supportAnchorX: X.mitigative,
      }),
    ],
    edges: [
      edge("mw-e1", "mw-threat-dose-failure", "mw-barrier-residual"),
      edge("mw-e2", "mw-barrier-residual", "mw-top-event"),
      edge("mw-e3", "mw-threat-filter-breakthrough", "mw-barrier-clarifier"),
      edge("mw-e4", "mw-barrier-clarifier", "mw-top-event"),
      edge("mw-e5", "mw-threat-backflow", "mw-barrier-backflow-program"),
      edge("mw-e6", "mw-barrier-backflow-program", "mw-top-event"),
      edge("mw-e7", "mw-top-event", "mw-barrier-boil-advisory"),
      edge("mw-e8", "mw-barrier-boil-advisory", "mw-consequence-illness"),
      edge("mw-e9", "mw-top-event", "mw-barrier-flush-disinfect"),
      edge("mw-e10", "mw-barrier-flush-disinfect", "mw-consequence-regulator"),
      edge("mw-e11", "mw-factor-maint-backlog", "mw-barrier-clarifier", ESCALATION_EDGE_STYLE),
      edge("mw-e12", "mw-control-critical-spares", "mw-factor-maint-backlog", ESCALATION_EDGE_STYLE),
      edge("mw-e13", "mw-factor-comms-gap", "mw-barrier-boil-advisory", ESCALATION_EDGE_STYLE),
      edge("mw-e14", "mw-control-comms-drill", "mw-factor-comms-gap", ESCALATION_EDGE_STYLE),
    ],
  },
  {
    slug: "warehouse-ammonia-release",
    title: "Warehouse Ammonia Release",
    industry: "Manufacturing",
    topEvent: "Ammonia is released from the refrigeration system into occupied areas",
    contextNotes:
      "Industrial refrigeration example for food distribution facilities with contractor work, leak detection, and emergency isolation.",
    summary:
      "Covers mechanical damage, overpressure, and maintenance error in an ammonia refrigeration system serving a cold-storage warehouse.",
    highlights: ["Industrial safety", "Occupational exposure", "Emergency isolation"],
    nodes: [
      node("wa-top-event", "top_event", X.topEvent, 320, {
        title: "Ammonia is released from the refrigeration system into occupied areas",
        description: "Containment is lost and ammonia migrates into workspaces or loading areas.",
        context: "Cold-storage warehouse using centralized ammonia refrigeration.",
      }),
      node("wa-threat-forklift", "threat", X.threat, 120, {
        title: "Forklift impact damages exposed piping",
        description: "Vehicle movement in the engine room or dock area breaches a line or valve.",
        cause: "Mobile equipment strike",
        source: "Warehouse traffic near refrigeration assets",
      }),
      node("wa-threat-overpressure", "threat", X.threat, 320, {
        title: "Overpressure during plant upset",
        description: "A control failure drives pressure beyond equipment limits.",
        cause: "Process upset and relief path impairment",
        source: "Compressors and condensers",
      }),
      node("wa-threat-maintenance", "threat", X.threat, 520, {
        title: "Improper maintenance breaks containment",
        description: "A component is opened or reassembled incorrectly during service work.",
        cause: "Isolation or verification error",
        source: "Contractor maintenance task",
      }),
      node("wa-barrier-protection", "preventive_barrier", X.preventive, 120, {
        title: "Physical guards and traffic exclusion around piping",
        description: "Protects critical lines from mobile-equipment impact.",
        barrierType: "engineering",
        owner: "Facility Engineering",
        performanceStandard: "All exposed ammonia lines in traffic areas remain guarded.",
        verificationMethod: "Monthly walkdown and damage inspection.",
        frequency: "Monthly",
      }),
      node("wa-barrier-pressure", "preventive_barrier", X.preventive, 320, {
        title: "Pressure interlocks and relief path verification",
        description: "Trips equipment and confirms relief systems remain available during abnormal conditions.",
        barrierType: "engineering",
        owner: "Refrigeration Supervisor",
        performanceStandard: "Trips actuate before safe operating limits are exceeded.",
        verificationMethod: "Quarterly functional testing.",
        frequency: "Quarterly",
      }),
      node("wa-barrier-loto", "preventive_barrier", X.preventive, 520, {
        title: "Permit-to-work and lockout verification",
        description: "Requires positive isolation, gas testing, and supervisor sign-off before maintenance.",
        barrierType: "procedural",
        owner: "Maintenance Manager",
        performanceStandard: "No intrusive work proceeds without approved isolation verification.",
        verificationMethod: "Weekly permit audit and field observation.",
        frequency: "Weekly",
      }),
      node("wa-factor-training", "escalation_factor", X.preventive, 410, {
        title: "Temporary contractors are unfamiliar with plant hazards",
        description: "Workers may bypass isolation steps or enter restricted zones incorrectly.",
        factor: "Competency gap weakens preventive controls.",
        supportLane: "preventive",
        supportAnchorX: X.preventive,
      }),
      node("wa-control-induction", "escalation_factor_control", X.preventive, 620, {
        title: "Contractor ammonia-safety induction",
        description: "Requires site-specific competency confirmation before any maintenance task begins.",
        control: "Verified onboarding and escort requirement for contractors",
        supportLane: "preventive",
        supportAnchorX: X.preventive,
      }),
      node("wa-barrier-detectors", "mitigative_barrier", X.mitigative, 220, {
        title: "Fixed gas detection with alarm and ventilation response",
        description: "Detects release quickly and triggers local alarms and exhaust response.",
        barrierType: "engineering",
        owner: "Control Systems Team",
        performanceStandard: "Ammonia detection initiates alarms and extraction within design setpoints.",
        verificationMethod: "Monthly bump test and annual calibration.",
        frequency: "Monthly",
        chainIndex: 0,
      }),
      node("wa-barrier-evacuation", "mitigative_barrier", X.mitigative, 470, {
        title: "Emergency evacuation and hazmat response plan",
        description: "Directs occupant evacuation, muster accountability, and fire/hazmat coordination.",
        barrierType: "procedural",
        owner: "Site Emergency Coordinator",
        performanceStandard: "Occupants clear affected zones and response agencies are notified immediately.",
        verificationMethod: "Quarterly drill and debrief.",
        frequency: "Quarterly",
        chainIndex: 0,
      }),
      node("wa-consequence-exposure", "consequence", X.consequence, 220, {
        title: "Worker exposure and injury",
        description: "Employees or contractors inhale ammonia or suffer chemical burns.",
        impact: "Serious injury, medical treatment, and operational disruption.",
        severity: "critical",
      }),
      node("wa-consequence-shutdown", "consequence", X.consequence, 470, {
        title: "Facility shutdown and product loss",
        description: "The warehouse must halt operations while the incident is stabilized and investigated.",
        impact: "Inventory loss, downtime, and regulator attention.",
        severity: "high",
      }),
      node("wa-factor-egress", "escalation_factor", X.mitigative, 90, {
        title: "Muster routes are blocked by peak warehouse activity",
        description: "Workers lose time evacuating because paths are congested.",
        factor: "Poor egress readiness weakens mitigative response.",
        supportLane: "mitigative",
        supportAnchorX: X.mitigative,
      }),
      node("wa-control-drills", "escalation_factor_control", X.mitigative, 130, {
        title: "Shift-based evacuation drills and route audits",
        description: "Confirms exits, muster points, and traffic controls remain workable across shifts.",
        control: "Routine evacuation drill and route-clearance verification",
        supportLane: "mitigative",
        supportAnchorX: X.mitigative,
      }),
    ],
    edges: [
      edge("wa-e1", "wa-threat-forklift", "wa-barrier-protection"),
      edge("wa-e2", "wa-barrier-protection", "wa-top-event"),
      edge("wa-e3", "wa-threat-overpressure", "wa-barrier-pressure"),
      edge("wa-e4", "wa-barrier-pressure", "wa-top-event"),
      edge("wa-e5", "wa-threat-maintenance", "wa-barrier-loto"),
      edge("wa-e6", "wa-barrier-loto", "wa-top-event"),
      edge("wa-e7", "wa-top-event", "wa-barrier-detectors"),
      edge("wa-e8", "wa-barrier-detectors", "wa-consequence-exposure"),
      edge("wa-e9", "wa-top-event", "wa-barrier-evacuation"),
      edge("wa-e10", "wa-barrier-evacuation", "wa-consequence-shutdown"),
      edge("wa-e11", "wa-factor-training", "wa-barrier-loto", ESCALATION_EDGE_STYLE),
      edge("wa-e12", "wa-control-induction", "wa-factor-training", ESCALATION_EDGE_STYLE),
      edge("wa-e13", "wa-factor-egress", "wa-barrier-evacuation", ESCALATION_EDGE_STYLE),
      edge("wa-e14", "wa-control-drills", "wa-factor-egress", ESCALATION_EDGE_STYLE),
    ],
  },
  {
    slug: "clinical-medication-error",
    title: "Clinical Medication Error",
    industry: "Healthcare",
    topEvent: "A patient receives the wrong high-risk medication dose",
    contextNotes:
      "Hospital medication-safety example focused on prescribing, dispensing, bedside administration, and rapid response.",
    summary:
      "Illustrates how order-entry, pharmacy verification, and bedside checks work together to prevent a severe medication event.",
    highlights: ["Healthcare", "Patient safety", "Clinical governance"],
    nodes: [
      node("cm-top-event", "top_event", X.topEvent, 320, {
        title: "A patient receives the wrong high-risk medication dose",
        description: "Medication reaches the patient at a dose or concentration inconsistent with the approved order.",
        context: "Acute-care hospital using electronic prescribing and smart infusion pumps.",
      }),
      node("cm-threat-order", "threat", X.threat, 120, {
        title: "Incorrect order entered in the EHR",
        description: "Prescriber selects the wrong dose or patient parameter in the order set.",
        cause: "Human factors in order entry",
        source: "Electronic prescribing workflow",
      }),
      node("cm-threat-dispense", "threat", X.threat, 320, {
        title: "Pharmacy dispenses wrong concentration",
        description: "Preparation or labeling error creates a mismatch between the order and product.",
        cause: "Compounding or dispensing error",
        source: "Pharmacy workflow",
      }),
      node("cm-threat-bedside", "threat", X.threat, 520, {
        title: "Bedside administration bypasses final checks",
        description: "Barcode or independent double-check steps are skipped under time pressure.",
        cause: "Workflow override during busy clinical conditions",
        source: "Medication administration at bedside",
      }),
      node("cm-barrier-cds", "preventive_barrier", X.preventive, 120, {
        title: "Dose-range decision support in the EHR",
        description: "Flags nonstandard doses based on patient age, weight, and renal function.",
        barrierType: "engineering",
        owner: "Clinical Informatics",
        performanceStandard: "High-risk medication orders outside defined limits trigger hard-stop review.",
        verificationMethod: "Monthly override and alert review.",
        frequency: "Monthly",
      }),
      node("cm-barrier-pharmacy", "preventive_barrier", X.preventive, 320, {
        title: "Independent pharmacist verification",
        description: "Requires a second check of dose, concentration, and patient suitability before release.",
        barrierType: "human",
        owner: "Pharmacy Services",
        performanceStandard: "All high-risk medications receive independent verification before dispensing.",
        verificationMethod: "Weekly audit of verification records.",
        frequency: "Weekly",
      }),
      node("cm-barrier-bcma", "preventive_barrier", X.preventive, 520, {
        title: "Barcode medication administration and bedside double-check",
        description: "Confirms patient identity, medication, and dose at the point of care.",
        barrierType: "procedural",
        owner: "Nursing Leadership",
        performanceStandard: "No high-risk medication is administered without barcode confirmation and documented check.",
        verificationMethod: "Monthly compliance report and observation.",
        frequency: "Monthly",
      }),
      node("cm-factor-alert-fatigue", "escalation_factor", X.preventive, 410, {
        title: "Frequent noncritical alerts create alert fatigue",
        description: "Clinicians become more likely to override important warnings.",
        factor: "Usability weakness reduces preventive effectiveness.",
        supportLane: "preventive",
        supportAnchorX: X.preventive,
      }),
      node("cm-control-alert-review", "escalation_factor_control", X.preventive, 620, {
        title: "Quarterly optimization of high-risk medication alerts",
        description: "Removes low-value warnings and tightens critical hard stops.",
        control: "Governed alert review with pharmacy and physician input",
        supportLane: "preventive",
        supportAnchorX: X.preventive,
      }),
      node("cm-barrier-rapid-response", "mitigative_barrier", X.mitigative, 220, {
        title: "Rapid clinical assessment and antidote protocol",
        description: "Triggers immediate escalation, patient monitoring, and reversal treatment where indicated.",
        barrierType: "procedural",
        owner: "Rapid Response Team",
        performanceStandard: "Suspected severe medication events receive immediate clinical review.",
        verificationMethod: "Post-event case review and mock code practice.",
        frequency: "Quarterly",
        chainIndex: 0,
      }),
      node("cm-barrier-disclosure", "mitigative_barrier", X.mitigative, 470, {
        title: "Disclosure, incident review, and care-plan adjustment",
        description: "Coordinates patient communication, root-cause review, and corrective actions.",
        barrierType: "procedural",
        owner: "Patient Safety Office",
        performanceStandard: "Serious medication events are disclosed and reviewed within policy timeframes.",
        verificationMethod: "Monthly patient-safety committee review.",
        frequency: "Monthly",
        chainIndex: 0,
      }),
      node("cm-consequence-harm", "consequence", X.consequence, 220, {
        title: "Patient deterioration or serious harm",
        description: "The patient experiences an adverse drug event requiring intervention.",
        impact: "Clinical harm, extended stay, or potential fatality.",
        severity: "critical",
      }),
      node("cm-consequence-accreditation", "consequence", X.consequence, 470, {
        title: "Reportable sentinel event and reputational damage",
        description: "The hospital faces mandatory review, corrective action, and external scrutiny.",
        impact: "Regulatory reporting, legal exposure, and loss of confidence.",
        severity: "high",
      }),
      node("cm-factor-staffing", "escalation_factor", X.mitigative, 90, {
        title: "Critical care coverage is thin during peak demand",
        description: "Escalation and treatment may be delayed when rapid-response resources are stretched.",
        factor: "Resource strain weakens mitigative response.",
        supportLane: "mitigative",
        supportAnchorX: X.mitigative,
      }),
      node("cm-control-escalation-drill", "escalation_factor_control", X.mitigative, 130, {
        title: "High-risk medication event drills and staffing triggers",
        description: "Ensures backup coverage and immediate escalation pathways during surges.",
        control: "Escalation trigger and surge staffing protocol",
        supportLane: "mitigative",
        supportAnchorX: X.mitigative,
      }),
    ],
    edges: [
      edge("cm-e1", "cm-threat-order", "cm-barrier-cds"),
      edge("cm-e2", "cm-barrier-cds", "cm-top-event"),
      edge("cm-e3", "cm-threat-dispense", "cm-barrier-pharmacy"),
      edge("cm-e4", "cm-barrier-pharmacy", "cm-top-event"),
      edge("cm-e5", "cm-threat-bedside", "cm-barrier-bcma"),
      edge("cm-e6", "cm-barrier-bcma", "cm-top-event"),
      edge("cm-e7", "cm-top-event", "cm-barrier-rapid-response"),
      edge("cm-e8", "cm-barrier-rapid-response", "cm-consequence-harm"),
      edge("cm-e9", "cm-top-event", "cm-barrier-disclosure"),
      edge("cm-e10", "cm-barrier-disclosure", "cm-consequence-accreditation"),
      edge("cm-e11", "cm-factor-alert-fatigue", "cm-barrier-cds", ESCALATION_EDGE_STYLE),
      edge("cm-e12", "cm-control-alert-review", "cm-factor-alert-fatigue", ESCALATION_EDGE_STYLE),
      edge("cm-e13", "cm-factor-staffing", "cm-barrier-rapid-response", ESCALATION_EDGE_STYLE),
      edge("cm-e14", "cm-control-escalation-drill", "cm-factor-staffing", ESCALATION_EDGE_STYLE),
    ],
  },
];

export const EXAMPLE_PROJECTS_BY_SLUG = Object.fromEntries(
  EXAMPLE_PROJECTS.map((example) => [example.slug, example]),
) as Record<string, ExampleProject>;
